version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

install:
    - cmd: >-
          call cudaInstallAppveyor.cmd
    - vcpkg update
    - vcpkg install --featurepackages boost-system:x64-windows boost-program-options:x64-windows boost-thread:x64-windows boost-filesystem:x64-windows

before_build:
    - md build
    - cd build
    - cmake -G "Visual Studio 14 2015" -A x64 -T v140,host=x64  -DPopSift_BUILD_EXAMPLES:BOOL=OFF -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
    - ls -l

build:
  verbosity: detailed
  project: $(APPVEYOR_BUILD_FOLDER)\build\PopSift.sln
  parallel: true

cache:
  c:\tools\vcpkg\installed\